CREATE table newest AS
  SELECT "REPLACE THIS LINE WITH YOUR SOLUTION";


CREATE table dog_movies AS 
  SELECT "REPLACE THIS LINE WITH YOUR SOLUTION";


CREATE table leads AS 
  SELECT "REPLACE THIS LINE WITH YOUR SOLUTION";


CREATE table long_movies AS 
  SELECT "REPLACE THIS LINE WITH YOUR SOLUTION";

